version: "3"
services:
  app:
    container_name: hackx
    restart: always
    build: .
    ports:
      - "3000:3003"
    links:
      - mongo
    command: npm start
  mongo:
    container_name: mongi
    image: mongo
    volumes:
      - .:/data/db
    ports:
      - "27017:27017"
