version: "3"
services:
  app:
    container_name: app
    restart: always
    image: diptochakrabarty/cc-cet:v2
    ports:
      - "85:85"
    links:
      - mongo
    command: npm start
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - .:/data/db
    ports:
      - "27017:27017"
