version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - ./*:/root/app/
   #   -  package.json:/root/app/package.json
    #  -  /root/app/node_modules 
   # copy:  ./package.json  /root/app/
    command: npm start
    ports:
      - "81:81"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./*:/data/db
    ports:
      - "27017:27017"
