version: "3"
services:
  app:
    container_name: app
    restart: always
    image: # ADD PREBUILT IMAGE LINK HERE
    command: npm start
    ports:
      - "81:81"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - .:/data/db
    ports:
      - "27017:27017"
