version: "3.1"
services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: Web/Dockerfile
    ports:
    - 80:80
    networks:
    - common-entry-test_default  
    - free-slot-finder_default
    - git-and-me-hack-insider_default
    volumes:
    - ./Web/nginx.conf:/etc/nginx/nginx.conf
    - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: on-failure


networks:
    common-entry-test_default:
        external: true
    free-slot-finder_default:
        external: true
    git-and-me-hack-insider_default:
        external: true
