version: "3"
services:
    frontend:
        container_name: frontend
 	restart: always
	image: react_appv3
       
        ports:
            - "8080:3000"
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: vikasraj/awesome_server
        ports:
            - "3006:3000"
    mongli:
        container_name: mongli
        image: mongo
        volumes:
            - .:/data/db

        ports:
            - '27020:27017'
