version: "3"
services:
  mongi:
    container_name: monge
    image: mongo
    volumes:
      - .:/data/db
    ports:
      - "27020:27017"
  hack:
    container_name: webinar
    image: webinar:v2
    restart: always
    ports:
      - 3006:3000
