version: "3"
services:
  mongi:
    container_name: mongi
    image: mongo
    volumes:
      - .:/data/db
    ports:
      - "27018:27017"
  hack:
    container_name: webinar
    image: webflow 
    restart: always
    ports:
      - 3005:3000
