version: "3"
services:
  mongi:
    container_name: mongi
    image: mongo
    volumes:
      - .:/data/db
    ports:
      - "27017:27017"
  hack:
    container_name: hack
    image: diptochakrabarty/hack:v2
    restart: always
    ports:
      - 3002:3000

